version: '3.8'

services:
  app:
    build: .
    ports:
      - "4567:4567"  
    environment:
      - NODE_ENV=development
      - PORT=4567    
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules  
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
